# Generated by Django 5.2.8 on 2026-02-08 19:49

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_image',
            field=models.ImageField(upload_to=core.models.get_hashed_file_path, validators=[core.validators.validate_file_size, core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
